# Generated by Django 5.2.8 on 2025-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
