# Generated by Django 6.0 on 2026-01-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
